-- <C-]> Jump to func defention
-- <C-k> Show documentation
-- gg0vG"+y  Copy all content into + buffer which can be accessible outside neovim
-- gf format the document
-- ciw change inner word
-- diw delete inner word (the word the cursor is in)
-- {  or } move up or down by one paragraph
-- gd jump to function defention
-- <C-^> jump to previous buffer
-- 
